apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/tekton/tasks/base
  - ../../../manifests/tekton/pipelines/base
  - ../../../manifests/tekton/configmaps/base
  - ../../../manifests/tekton/cronjobs/base

namespace: okd-team
