apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - okd-coreos-4.13-prod-create-daily.yaml
  - okd-coreos-4.14-prod-create-daily.yaml
  - okd-coreos-4.15-prod-create-daily.yaml
  - tekton-cleanup-daily.yaml
