apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cosa-build-baseos.yaml
  - cosa-build-extensions.yaml
  - cosa-buildextend.yaml
  - cosa-init.yaml
  - cosa-push-container.yaml
  - cosa-test.yaml
  - cosa-upload-s3.yaml
  - cosa-generate-release-meta.yaml
  - rpm-artifacts-copy.yaml
  - notify-matrix.yaml
  - build-layer.yaml
