apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cron-trig
      bindings:
      - ref: cron-binding
      template:
        ref: pipeline-template